version: '3.9'

services:
  postgres:
    image: ramsrib/pgvector
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
      - ./postgres/scripts:/docker-entrypoint-initdb.d

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
      - "11431:11431"
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 2 &&
      ollama pull qwen3:8b &&
      ollama pull mxbai-embed-large &&
      wait
      "
    volumes:
      - ./ollama:/root/.ollama
  slavik-llm: #for stepan only!
    image: touchme245/slavik-llm:latest
    container_name: slavik-llm
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - ollama
      - postgres
    environment:
      OLLAMA_URL: http://ollama:11434
      DB_URL: jdbc:postgresql://postgres:5432/ragdb

volumes:
  pgdata:
    driver: local