-- =============================================
-- Users
-- =============================================

CREATE TABLE IF NOT EXISTS public.users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

ALTER TABLE public.users
    OWNER TO postgres;

-- =============================================
-- Chat -> User relation
-- =============================================

ALTER TABLE public.chat
    ADD COLUMN IF NOT EXISTS user_id INTEGER;

ALTER TABLE public.chat
    ADD CONSTRAINT fk_chat_user
        FOREIGN KEY (user_id)
            REFERENCES public.users (id)
            ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_chat_user_id
    ON public.chat(user_id);